version: "3.8"
services:
  ollama:
    image: ollama/ollama:latest
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    # Run ollama serve in the foreground - fixes restart loop
    command: serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
      
  braincells:
    build:
      context: ./aisheets
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - HF_TOKEN=${HF_TOKEN:-}  # Recommended: Hugging Face token for model access
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}  # Optional: OpenAI API key
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}  # Optional: Anthropic API key
      - MODEL_ENDPOINT_URL=${MODEL_ENDPOINT_URL:-}  # Optional: Custom model endpoint
      - MODEL_ENDPOINT_NAME=${MODEL_ENDPOINT_NAME:-}  # Optional: Custom model name
      - APP_NAME=Brain Cells
      - APP_LOGO=🧠
      - OLLAMA_HOST=http://ollama:11434  # Connect to Ollama service
    volumes:
      - ./data:/app/data  # Mount local data directory
    restart: unless-stopped
    depends_on:
      - ollama

volumes:
  ollama_data: