import React, { useState } from 'react';
import { useSpreadsheetStore } from '../../stores/spreadsheet-store';
import { useProviderStore } from '../../stores/provider-store';
import { ColumnType } from '../../types/database';
import { Dialog, Input, Select, Button } from '../common';

interface AddColumnDialogProps {
  isOpen: boolean;
  onClose: () => void;
}

export function AddColumnDialog({ isOpen, onClose }: AddColumnDialogProps) {
  const { addColumn, currentTableView } = useSpreadsheetStore();
  const { providers, getCurrentProvider } = useProviderStore();

  const [columnName, setColumnName] = useState('');
  const [columnType, setColumnType] = useState<ColumnType>(ColumnType.Input);
  const [prompt, setPrompt] = useState('');
  const [providerId, setProviderId] = useState('');
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState('');

  const currentProvider = getCurrentProvider();

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError('');

    if (!columnName.trim()) {
      setError('Column name is required');
      return;
    }

    if (columnType === ColumnType.Output && !prompt.trim()) {
      setError('Prompt is required for AI output columns');
      return;
    }

    if (columnType === ColumnType.Output && !providerId && !currentProvider) {
      setError('Please select an AI provider for output columns');
      return;
    }

    setIsSubmitting(true);
    try {
      const selectedProviderId = providerId || currentProvider?.id || undefined;

      await addColumn(
        columnName.trim(),
        columnType,
        columnType === ColumnType.Output ? prompt.trim() : undefined,
        columnType === ColumnType.Output ? selectedProviderId : undefined
      );

      // Reset form
      setColumnName('');
      setColumnType(ColumnType.Input);
      setPrompt('');
      setProviderId('');
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to add column');
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClose = () => {
    if (!isSubmitting) {
      setColumnName('');
      setColumnType(ColumnType.Input);
      setPrompt('');
      setProviderId('');
      setError('');
      onClose();
    }
  };

  const columnTypeOptions = [
    { value: ColumnType.Input, label: 'Input - User-entered data' },
    { value: ColumnType.Output, label: 'AI Output - Generated by AI' },
    { value: ColumnType.Formula, label: 'Formula - Computed value' },
  ];

  const providerOptions = [
    { value: '', label: currentProvider ? `Default (${currentProvider.name})` : 'Select provider...' },
    ...providers.map((provider) => ({
      value: provider.id,
      label: provider.name,
    })),
  ];

  return (
    <Dialog
      isOpen={isOpen}
      onClose={handleClose}
      title="Add Column"
      maxWidth="lg"
      footer={
        <>
          <Button variant="secondary" onClick={handleClose} disabled={isSubmitting}>
            Cancel
          </Button>
          <Button variant="primary" onClick={handleSubmit} disabled={isSubmitting}>
            {isSubmitting ? 'Adding...' : 'Add Column'}
          </Button>
        </>
      }
    >
      <form onSubmit={handleSubmit} className="space-y-4">
        {error && (
          <div className="p-3 bg-red-50 border border-red-200 rounded-lg text-red-700 text-sm">
            {error}
          </div>
        )}

        <Input
          label="Column Name"
          value={columnName}
          onChange={(e) => setColumnName(e.target.value)}
          placeholder="e.g., Product Name, Description, Category"
          fullWidth
          required
          disabled={isSubmitting}
        />

        <Select
          label="Column Type"
          value={columnType}
          onChange={(e) => setColumnType(e.target.value as ColumnType)}
          options={columnTypeOptions}
          fullWidth
          disabled={isSubmitting}
        />

        {columnType === ColumnType.Output && (
          <>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">
                AI Prompt Template
              </label>
              <textarea
                value={prompt}
                onChange={(e) => setPrompt(e.target.value)}
                placeholder="e.g., Write a product description for {{Product Name}} in the {{Category}} category"
                className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 min-h-[100px]"
                disabled={isSubmitting}
                required
              />
              <p className="mt-1 text-xs text-gray-500">
                Use &#123;&#123;Column Name&#125;&#125; to reference values from other columns
              </p>
            </div>

            <Select
              label="AI Provider"
              value={providerId}
              onChange={(e) => setProviderId(e.target.value)}
              options={providerOptions}
              fullWidth
              disabled={isSubmitting || providers.length === 0}
            />

            {providers.length === 0 && (
              <p className="text-sm text-yellow-700 bg-yellow-50 border border-yellow-200 rounded-lg p-3">
                No AI providers configured. Please set up a provider in settings first.
              </p>
            )}
          </>
        )}

        {columnType === ColumnType.Formula && (
          <div className="p-3 bg-blue-50 border border-blue-200 rounded-lg text-blue-700 text-sm">
            Formula columns are coming soon! You'll be able to create computed values using expressions.
          </div>
        )}

        {currentTableView && (
          <div className="text-sm text-gray-600">
            This column will be added to the <strong>{currentTableView.dataset.name}</strong> dataset
          </div>
        )}
      </form>
    </Dialog>
  );
}
