use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};

/// Dataset represents a collection of data rows with columns
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Dataset {
    pub id: String,
    pub name: String,
    pub description: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Dataset {
    pub fn new(name: String, description: Option<String>) -> Self {
        let now = Utc::now();
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            name,
            description,
            created_at: now,
            updated_at: now,
        }
    }
}

/// Column types for spreadsheet data
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum ColumnType {
    /// Input column (user-provided data)
    Input,
    /// Output column (generated by AI)
    Output,
    /// Formula column (computed from other columns)
    Formula,
}

impl std::fmt::Display for ColumnType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ColumnType::Input => write!(f, "input"),
            ColumnType::Output => write!(f, "output"),
            ColumnType::Formula => write!(f, "formula"),
        }
    }
}

impl std::str::FromStr for ColumnType {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "input" => Ok(ColumnType::Input),
            "output" => Ok(ColumnType::Output),
            "formula" => Ok(ColumnType::Formula),
            _ => Err(anyhow::anyhow!("Invalid column type: {}", s)),
        }
    }
}

/// Column definition
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Column {
    pub id: String,
    pub dataset_id: String,
    pub name: String,
    pub column_type: ColumnType,
    /// AI prompt for output columns
    pub prompt: Option<String>,
    /// Provider ID to use for this column
    pub provider_id: Option<String>,
    /// Position in the table
    pub position: i32,
    pub created_at: DateTime<Utc>,
}

impl Column {
    pub fn new(
        dataset_id: String,
        name: String,
        column_type: ColumnType,
        position: i32,
    ) -> Self {
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            dataset_id,
            name,
            column_type,
            prompt: None,
            provider_id: None,
            position,
            created_at: Utc::now(),
        }
    }

    pub fn with_prompt(mut self, prompt: String) -> Self {
        self.prompt = Some(prompt);
        self
    }

    pub fn with_provider(mut self, provider_id: String) -> Self {
        self.provider_id = Some(provider_id);
        self
    }
}

/// Cell execution status
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum CellStatus {
    /// Cell is waiting to be processed
    Pending,
    /// Cell is currently being processed
    Processing,
    /// Cell has been successfully processed
    Complete,
    /// Cell processing failed
    Error,
}

impl std::fmt::Display for CellStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CellStatus::Pending => write!(f, "pending"),
            CellStatus::Processing => write!(f, "processing"),
            CellStatus::Complete => write!(f, "complete"),
            CellStatus::Error => write!(f, "error"),
        }
    }
}

impl std::str::FromStr for CellStatus {
    type Err = anyhow::Error;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s.to_lowercase().as_str() {
            "pending" => Ok(CellStatus::Pending),
            "processing" => Ok(CellStatus::Processing),
            "complete" => Ok(CellStatus::Complete),
            "error" => Ok(CellStatus::Error),
            _ => Err(anyhow::anyhow!("Invalid cell status: {}", s)),
        }
    }
}

/// Cell data
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Cell {
    pub id: String,
    pub dataset_id: String,
    pub column_id: String,
    pub row_index: i32,
    pub value: Option<String>,
    pub status: CellStatus,
    pub error: Option<String>,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
}

impl Cell {
    pub fn new(dataset_id: String, column_id: String, row_index: i32) -> Self {
        let now = Utc::now();
        Self {
            id: uuid::Uuid::new_v4().to_string(),
            dataset_id,
            column_id,
            row_index,
            value: None,
            status: CellStatus::Pending,
            error: None,
            created_at: now,
            updated_at: now,
        }
    }

    pub fn with_value(mut self, value: String) -> Self {
        self.value = Some(value);
        self.status = CellStatus::Complete;
        self.updated_at = Utc::now();
        self
    }

    pub fn with_error(mut self, error: String) -> Self {
        self.error = Some(error);
        self.status = CellStatus::Error;
        self.updated_at = Utc::now();
        self
    }

    pub fn set_processing(&mut self) {
        self.status = CellStatus::Processing;
        self.updated_at = Utc::now();
    }
}

/// Row data (combination of cells from all columns)
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Row {
    pub index: i32,
    pub cells: std::collections::HashMap<String, Cell>,
}

impl Row {
    pub fn new(index: i32) -> Self {
        Self {
            index,
            cells: std::collections::HashMap::new(),
        }
    }

    pub fn add_cell(&mut self, column_id: String, cell: Cell) {
        self.cells.insert(column_id, cell);
    }

    pub fn get_cell(&self, column_id: &str) -> Option<&Cell> {
        self.cells.get(column_id)
    }

    pub fn get_cell_value(&self, column_id: &str) -> Option<&String> {
        self.cells.get(column_id)?.value.as_ref()
    }
}

/// Table view combining dataset, columns, and rows
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TableView {
    pub dataset: Dataset,
    pub columns: Vec<Column>,
    pub rows: Vec<Row>,
    pub total_rows: usize,
}

impl TableView {
    pub fn new(dataset: Dataset, columns: Vec<Column>, rows: Vec<Row>) -> Self {
        let total_rows = rows.len();
        Self {
            dataset,
            columns,
            rows,
            total_rows,
        }
    }
}
